// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsQJT2xWsK-xv1Q578PUgwfmgrPrM4ywI',
    appId: '1:375358086577:web:403418034706f7812c3190',
    messagingSenderId: '375358086577',
    projectId: 'fir-c292f',
    authDomain: 'fir-c292f.firebaseapp.com',
    storageBucket: 'fir-c292f.appspot.com',
    measurementId: 'G-REGLBFTKWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ZPTHMO2MZfnQyWFF4-HdytX9N-Nnbw8',
    appId: '1:375358086577:android:058531ecf591ae762c3190',
    messagingSenderId: '375358086577',
    projectId: 'fir-c292f',
    storageBucket: 'fir-c292f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKIHAKWTuLSe_uQUg1_dky3eOLEBqsFNM',
    appId: '1:375358086577:ios:c920a0993edef0a32c3190',
    messagingSenderId: '375358086577',
    projectId: 'fir-c292f',
    storageBucket: 'fir-c292f.appspot.com',
    iosClientId: '375358086577-36l3fka4b9jmafplfpfa3aaeonu44lnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.class20',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKIHAKWTuLSe_uQUg1_dky3eOLEBqsFNM',
    appId: '1:375358086577:ios:56757a1b91e514f42c3190',
    messagingSenderId: '375358086577',
    projectId: 'fir-c292f',
    storageBucket: 'fir-c292f.appspot.com',
    iosClientId: '375358086577-25ceo60jhjlmqnp5kii46e806ku71h9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.class20.RunnerTests',
  );
}
